groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
  - name: container_status_checks
    rules:
      - alert: ContainerDown
        expr: count by (container) (container_last_seen <= time() - 60) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.container }} is down"
          description: "The container {{ $labels.container }} has not been seen for more than 1 minute."