info:
  version: 1.0.0
  title: tool-compose
  description: |
    Integration of k6, Prometheus, and GitHub for comprehensive capability.

low_code:
  property:
    system_name: Cinema

  method:
    - name: test-compose-stress_testing_smoke_testing_and_repository_report
      parameter:
        service_name: service name
        number_of_virtual_user: 1 <= n <= 5
      description: |
        Perform stress testing and smoke testing on microservices simultaneously while monitoring the testing status. Then, for the microservices that did not pass the tests, retrieve their recent activity within the past week, including the activity of each team member in their respective repositories. Finally, aggregate and present the results.  
      access: protected
      protected:
          - supervisor
      body:
        - prometheus.set-prometheus-edit_alert_rules: null
        - k6.test-k6-stress_testing_all_service: null
        - prometheus.monitor-prometheus-all_service_alert: null
        - toolkit-parse-json:
            jsonpath: .....${prometheus.monitor-prometheus-all_service_alert}
        - toolkit-flow-foreach:
            array: ${toolkit-parse-json}
            element_name: service_name
            method: github.get-github-service_past_week_team_activity
            method_parameter_json: {"service_name": "${service_name}"}